### ISSUE TITLE
米印の取扱い

### ISSUE THREAD

**Issue by southly** [hmdev/AozoraEpub3#6]
```
※［＃米印、1-2-8］｜明かり《ライト》
```
というテキストがあったとき、現在(1.1.0b38)以下の用に変換されています。
```
  <p>｜明<ruby>かり<rt>ライト</rt></ruby></p>
```
期待される結果は以下ではないでしょうか。
```
  <p>※<ruby>明かり<rt>ライト</rt></ruby></p>
```

**Comment by hmdev** [comment]
特殊文字注記の置換字のエスケープ処理に内部で※を使っているのですが、※［＃米印、1-2-8］は※※になっていなかったため ※｜ がエスケープされた文字扱いになっていました。
一応修正してコミットしましたが、置換処理等で不具合が無いか確認中です。

**Comment by hmdev** [comment]
外字注記変換時に※［＃米印、1-2-8］を※※に置き換え、エスケープ文字のチェックは、前方の※の連続も見るようにしました。
他の前方参照や目次文字取得部分の文字置換も修正し、※エスケープ周りで怪しそうな部分は一通りつぶせたと思います。

**Comment by southly** [comment]
対応ありがとうございました。

AozoraEpub3 は重宝していますので、また何か見つけた時は報告させていただきます。
